package de.tum.claritypipeline.model.classification;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import lombok.*;

import java.io.Serializable;
import java.util.List;

/**
 * Response payload generated by the paraphrasing model within {@link de.tum.claritypipeline.strategy.PagStrategy}.
 * <p>
 * Contains the list of semantically equivalent question formulations that will subsequently be classified
 * and aggregated. Persisted paraphrases allow the pipeline to reuse expensive generations across runs.
 * </p>
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ParaphrasingResult implements Serializable {

    public static final String JSON_SCHEME = """
            {
                "paraphrases": [
                    <STRING | Paraphrase for the input>
                ]
            }
            """;
    @JsonProperty("paraphrases")
    @JsonPropertyDescription("Collection of paraphrased user questions used for downstream classification")
    private List<String> paraphrases;
}
