#================================== Description ========================================
# Docker Compose file to build the clarity-models image
#
# To start the models service, you can use either of the following methods:
#   1. From the command line, navigate to `clarity-models/` and run
#        `docker compose up -d`
#   2. Use the IntelliJ Docker plugin to run this file as a Docker Compose configuration.
#
# To force a rebuild of the image, use:
#        `docker compose build --no-cache`
#=======================================================================================

services:
  models:
    image: "clarity-models-models:latest"
    container_name: "clarity-models"
    ports:
      - "6006:6006"
      - "8000:8000"
    build:
      context: ..
      dockerfile: "clarity-models/Dockerfile"
    platform: "linux/amd64"
    volumes:
      - "./.artifacts:/app/.artifacts"
      - "./models:/app/models"
      - "./dto:/app/dto"
      - "./utils:/app/utils"
      - "./app.py:/app/app.py"
      - "./logging.yaml:/app/logging.yaml"
      - "./models.yaml:/app/models.yaml"
      - "../clarity-dataset/data:/app/data"
      - "../assets/taxonomy:/app/taxonomy"
      - "../assets/prompts:/app/prompts"
    environment:
      - "HF_HOME=/app/cache"
      - "PYTHONUNBUFFERED=1"
      - "TOKENIZERS_PARALLELISM=false"
      - "TOGETHER_API_KEY=${TOGETHER_API_KEY:-}"
      - "TAXONOMY_FILE=/app/taxonomy/clarity-categories.yaml"
      - "FINE_TUNE_PROMPT_FILE=/app/prompts/lora.yaml"
      - "ZERO_SHOT_PROMPT_FILE=/app/prompts/zero-shot.yaml"
      - "FEW_SHOT_PROMPT_FILE=/app/prompts/few-shot.yaml"
    restart: "unless-stopped"